### ISSUE TITLE
Uncaught TypeError: pane.onDidMoveItem is not a function

### ISSUE THREAD

**Issue by bedge** [MoOx/atom-smart-tab-name#11]
Tried to split right with 2 files open, name tmux.conf and tmux.conf.save

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [smart-tab-name](https://github.com/MoOx/atom-smart-tab-name) package, v1.0.4
### Stack Trace

Uncaught TypeError: pane.onDidMoveItem is not a function

```
At /Users/bedge/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119

TypeError: pane.onDidMoveItem is not a function
  at /Users/bedge/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119:27
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
  at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:214:19)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:720:23)
  at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
  at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:427:31)
  at Object.addElementCommands.tabs:split-right (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:135:26)
  at space-pen-ul.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "semanticolor",
      "ctags-status",
      "select-rectangle"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-ctags, v4.3.0
atom-html-preview, v0.1.11
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
atom-python-debugger, v0.3.4
autocomplete-ctags, v0.3.2
autocomplete-plus-python-jedi, v0.3.6
color-picker, v2.0.13
color-tabs, v0.1.8
colorful-json, v1.0.0
docblockr, v0.7.3
git-diff-details, v0.20.0
git-log, v0.4.1
gradle-ci, v1.1.4
java-importer, v1.4.1
language-gradle, v0.0.3
language-groovy, v0.4.0
language-tmux, v0.4.0
linter, v1.8.1
linter-javac, v1.2.0
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
linter-shellcheck, v1.0.2
markdown-mindmap, v0.2.4
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.15.0
smart-tab-name, v1.0.4
tab-smart-sort, v0.1.4
tag, v0.3.0
tree-view-git-modified, v0.5.12
tree-view-git-status, v0.2.2
typewriter, v0.3.4

# Dev
No dev packages
```

**Comment by tbekaert** [comment]
I just had the same issue:

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.4
**Thrown From**: smart-tab-name package, v1.0.4

### Stack Trace

Uncaught TypeError: pane.onDidMoveItem is not a function

```
/Users/tbekaert/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119
Hide Stack Trace
TypeError: pane.onDidMoveItem is not a function
  at /Users/tbekaert/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119:27
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
  at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:214:19)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:720:23)
  at Pane.module.exports.Pane.splitDown (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:694:19)
  at atom-pane.atom.commands.add.pane:split-down (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:283:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

### Installed packages

```
├── atom-alignment@0.12.1
├── atom-beautify@0.28.14
├── atom-css-comb@2.0.1
├── atom-ternjs@0.8.2
├── atom-typescript@7.4.1
├── coffee-lint@0.7.3
├── dash@1.3.2
├── duplicate-line-or-selection@0.5.0
├── emmet@2.3.13
├── git-control@0.4.0
├── git-plus@5.4.7
├── highlight-line@0.11.0
├── highlight-selected@0.10.1
├── javascript-snippets@1.0.0
├── language-liquid@0.4.0
├── linter@1.8.1
├── linter-jshint@1.2.1
├── merge-conflicts@1.3.6
├── minimap@4.13.4
├── minimap-highlight-selected@4.3.1
├── pigments@0.17.1
├── project-manager@2.6.2
├── ruby-slim@0.2.0
├── save-session@0.15.7
├── set-syntax@0.3.0
├── smart-tab-name@1.0.4
├── spacegray-eighties-ui@1.0.0
├── svg-preview@0.6.1
├── symbol-gen@1.0.0
├── term2@0.9.21
├── todo-show@0.16.0
├── tomorrow-night-eighties@0.4.0
└── tomorrow-night-eighties-syntax@0.6.1
```

**Comment by folletto** [comment]
Happened to me as well. 

Note that if Atom has the panels already open, it works. It just breaks when one tries to do a new split.

**Comment by folletto** [comment]
I don't know if it breaks something else, but just commenting out `@disposables pane.onDidMoveItem ->` seems fixing it.

**Comment by ben-eb** [comment]
Same issue here.

**Comment by fchevitarese** [comment]
I commented it out as @folletto said and it worked for me. 
As him, idk if it breaks anything... =D

**Comment by zuk** [comment]
Same here. Commenting out that line worked fine for me too.

**Comment by bmenant** [comment]
This PR #13 should fix this issue keeping the algorithm up, as far as I understood it. :wink:
