### ISSUE TITLE
Failed to activate the smart-tab-name package

### ISSUE THREAD

**Issue by nagkura** [MoOx/atom-smart-tab-name#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [smart-tab-name](https://github.com/MoOx/atom-smart-tab-name) package 1.0.5

### Stack Trace

Failed to activate the smart-tab-name package

```
At Cannot find module 'atom-simple-logger'

Error: Cannot find module 'atom-simple-logger'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Main.module.exports.Main.activate (/packages/atom-smart-tab-name-master/lib/main.coffee:25:13)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
auto-indent 0.5.0 
atom-beautify 0.32.5 
japanese-menu 1.14.0 
file-icons 2.1.21 
open-recent 5.0.0 
pigments 0.40.2 
project-manager 3.3.6 
smart-tab-name 1.0.5 
autocomplete-paths 2.12.2 
emmet 2.4.3 
imdone-atom 2.4.29 
tool-bar 1.1.7 
```

**Comment by MoOx** [comment]
It seems a package hasn't been installed correctly. Please try to reinstall.
